name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create environment with conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: victree
          python-version: 3.10
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false

      - name: Install dependencies
        run: |
          conda install --file requirements.txt
          pip install scgenome
          pip install .

      - name: Test executables
        run: |
          victree --help
          victree-simul --help

      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          conda install pytest
          pytest
